### ISSUE TITLE
I want all players in lobby can switch to monster (pls add setting)

### ISSUE THREAD

**Issue by ZAGROS0908** [ControlCompany/ControlCompany#81] opened 2024-01-15 18:02 UTC
I want all players in lobby can switch to monster (pls add setting)

**Comment by JustCallMeQuincy** [comment] 2024-01-15 18:06
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed** 2024-01-15 18:20 UTC
Labels: duplicate
