### ISSUE TITLE
Compatibility With LethalEscape mod

### ISSUE THREAD

**Issue by JesterFreeBird** [ControlCompany/ControlCompany#160] opened 2024-02-04 18:52 UTC
Since people want to play as inside monsters outside, this mod compatibility would be perfect. It would basically give every enemy the ability to enter/exit the facility like a masked controlled by the player.

**Comment by JustCallMeQuincy** [comment] 2024-02-04 22:09
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/95

**Closed by JustCallMeQuincy** 2024-02-04 22:09 UTC
Labels: duplicate
