### ISSUE TITLE
Door Desync

### ISSUE THREAD

**Issue by Autumnis** [ControlCompany/ControlCompany#90] opened 2024-01-16 08:25 UTC
If you walk through a door as a creature that cannot open a door, such as a spore lizard, the creature's body will remain at the door while the player sees it as if nothing happened.

**Comment by JustCallMeQuincy** [comment] 2024-01-16 09:11
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/82

**Closed by JustCallMeQuincy** 2024-01-16 09:11 UTC
Labels: duplicate
