### ISSUE TITLE
Option to allow everyone in the lobby to use the mod

### ISSUE THREAD

**Issue by JokerJosh1234** [ControlCompany/ControlCompany#179] opened 2024-02-19 12:02 UTC
It would be pretty cool if there was a config option to allow all players in the lobby to use the mod, or even specific players that the host can set from in the game (preferred option)

**Comment by JustCallMeQuincy** [comment] 2024-02-20 11:08
Closing as it's a duplicate of #2 
Check out that issue for more information

**Closed by JustCallMeQuincy** 2024-02-20 11:08 UTC
Labels: duplicate
