### ISSUE TITLE
Make monsters be able to walk across gaps

### ISSUE THREAD

**Issue by ShadowmeC3** [ControlCompany/ControlCompany#142] opened 2024-01-27 01:40 UTC
title.

you could make an invisible platform that you can walk on

because the jump mechanic isn't very realistic and you friends can easily tell you are the monster.

**Comment by JustCallMeQuincy** [comment] 2024-01-27 02:35
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/10
Feel free to leave further comments related to your idea in that thread

**Closed by JustCallMeQuincy** 2024-01-27 02:35 UTC
Labels: duplicate
