### ISSUE TITLE
Cant deal damage as monster

### ISSUE THREAD

**Issue by JWR19HTY** [ControlCompany/ControlCompany#73] opened 2024-01-15 03:04 UTC
just straight up can't kill my friends

**Comment by 12GaugeDr** [comment] 2024-01-15 03:09
Also having this issue.

**Comment by JWR19HTY** [comment] 2024-01-15 03:15
players can't die, even after falling

**Comment by blueski1** [comment] 2024-01-15 03:42
monsters cant do damage after killing them the first time, also if done while dead, you will be unable to move upon respawn. all players will eventually become immune to all damage

**Comment by mikalooloo** [comment] 2024-01-15 03:51
I was also having the issue where players cannot die at all, from player-controlled monsters to falling. If I disable LC_API, it works again.

**Comment by blueski1** [comment] 2024-01-15 03:57
> I was also having the issue where players cannot die at all, from player-controlled monsters to falling. If I disable/uninstall LC_API, it works again. Check to see if you have that installed.

I do and disabled it. I'll run with it rn

**Comment by RunnyMoney** [comment] 2024-01-15 04:08
> > I was also having the issue where players cannot die at all, from player-controlled monsters to falling. If I disable/uninstall LC_API, it works again. Check to see if you have that installed.
> 
> I do and disabled it. I'll run with it rn

Same issue you're facing, let me know if the LC_API disable fixes it.

**Comment by ietesla** [comment] 2024-01-15 04:12
This issue stinks...

**Comment by 12GaugeDr** [comment] 2024-01-15 04:16
There was an update to the LC-API that had fixed the issue! It's working as intended now!

**Comment by RunnyMoney** [comment] 2024-01-15 04:22
Correct LC-API 3.4.1 fixed players not dying, wasn't mod specific

**Comment by klampzlamps** [comment] 2024-01-15 04:53
closing issue as it's unrelated to the mod and an update to another mod fixes it

**Closed by klampzlamps** 2024-01-15 04:53 UTC
Labels: unrelated to mod
