### ISSUE TITLE
Stop mobs despawning

### ISSUE THREAD

**Issue by tinywolf46** [ControlCompany/ControlCompany#159] opened 2024-02-04 00:25 UTC
Is there a way to stop the mob from despawning when exiting mob mode?

as this would make it easier to hide it from friends

**Comment by JustCallMeQuincy** [comment] 2024-02-04 22:10
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/51

**Closed by JustCallMeQuincy** 2024-02-04 22:10 UTC
Labels: duplicate
