### ISSUE TITLE
Other players able to use monsters not just host.

### ISSUE THREAD

**Issue by DarkOwl020407** [ControlCompany/ControlCompany#151] opened 2024-01-30 05:37 UTC
This would be a game changer, we would be able to play prop hunt inside of Lethal company. Is this a possible task or not?

**Comment by JustCallMeQuincy** [comment] 2024-01-30 11:13
Closing as it's a duplicate of #2 
Feel free to add any suggestions there

**Closed by JustCallMeQuincy** 2024-01-30 11:13 UTC
Labels: duplicate
