### ISSUE TITLE
jester and nutcracker are broken

### ISSUE THREAD

**Issue by mijail1024** [ControlCompany/ControlCompany#46] opened 2024-01-13 22:37 UTC
jester can instantly go into rage mode after pressing (not holding) m2 and the nutcracker can shoot nonstop by just spamming m1

**Comment by Kelkios** [comment] 2024-01-13 23:24
I don't believe this is unintended behavior when it comes to the nutcracker, although I'd like to see a button to make the jester pop out without winding, it would make for some hilarious scares

**Comment by klampzlamps** [comment] 2024-01-15 06:28
Duplicate of #72

**Closed by klampzlamps** 2024-01-15 06:28 UTC
