### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by ShadowmeC3** [ControlCompany/ControlCompany#188] opened 2024-02-26 17:56 UTC
Basically add a way where when you leave the creature your controlling the creature will stay there.

I was thinking if you have AI control on when you leave it, then it will stay there. If you are controlling it then it will disappear. This way the body of mobs won't just disappear. Or if your playing as a mob your friends won't just never see it again.

Hopefully something like this gets added, thank you for reading.

**Comment by JustCallMeQuincy** [comment] 2024-02-26 19:27
Duplicate of #51 

Feel free to add any thoughts or ideas in that thread.

**Closed by JustCallMeQuincy** 2024-02-26 19:27 UTC
Labels: duplicate, feature request
