### ISSUE TITLE
Aggro Form on Monsters

### ISSUE THREAD

**Issue by ZachFNF** [ControlCompany/ControlCompany#152] opened 2024-01-31 02:14 UTC
add it soon please :D

**Comment by ZachFNF** [comment] 2024-01-31 02:16
it would be really freakin fun  and i hope it comes soon

**Comment by JustCallMeQuincy** [comment] 2024-02-02 20:13
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/78
Feel free to add more suggestions in that thread

**Closed by JustCallMeQuincy** 2024-02-02 20:13 UTC
Labels: duplicate

**Comment by ZachFNF** [comment] 2024-02-02 21:41
you wont add this?

**Comment by ZachFNF** [comment] 2024-02-02 21:42
it said you closed it as "not planned"

**Comment by JustCallMeQuincy** [comment] 2024-02-02 21:48
It's a duplicate, that's how those are closed
Refer to #78 on further developments on that request

**Comment by ZachFNF** [comment] 2024-02-02 22:08
oh ok great thanks
