### ISSUE TITLE
pass through hole

### ISSUE THREAD

**Issue by ELBuissont** [ControlCompany/ControlCompany#89] opened 2024-01-16 07:23 UTC
when you are a monster, you can't make the jump to pass through the hole in the building.
So can you do that you just walk on the void to go to the other side.

**Comment by JustCallMeQuincy** [comment] 2024-01-16 09:09
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/10

**Closed** 2024-01-16 09:09 UTC
Labels: duplicate
