### ISSUE TITLE
Duel system

### ISSUE THREAD

**Issue by Xaocsoul** [ControlCompany/ControlCompany#182] opened 2024-02-20 04:20 UTC
Basically a way to control the player without needing to despawn the entity

perhaps a second screen to show the players POV and you could control them using the arrow keys < and > to turn and the others to move backwards and forwards right shift to sprint and left ctrl to crouch

this is most likely extremely difficult to code in so it’s alright if it’s denied

**Comment by JustCallMeQuincy** [comment] 2024-02-20 11:09
Closing as it's a duplicate of #51 
Feel free to add your ideas to that thread

**Closed by JustCallMeQuincy** 2024-02-20 11:09 UTC
Labels: duplicate
