### ISSUE TITLE
Whitelist control

### ISSUE THREAD

**Issue by plechovka** [ControlCompany/ControlCompany#104] opened 2024-01-17 19:17 UTC
**Is your feature request related to a problem? Please describe.**
It is a request, ability to whitelist someone from friend list that is also able to control with this mod.

**Describe the solution you'd like**
Adding ability so I can choose who also can control the enemy

**Comment by JustCallMeQuincy** [comment] 2024-01-17 19:30
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed by JustCallMeQuincy** 2024-01-17 19:30 UTC
Labels: duplicate, feature request
