### ISSUE TITLE
More than a mic setting

### ISSUE THREAD

**Issue by Jack18m** [ControlCompany/ControlCompany#118] opened 2024-01-20 00:01 UTC
I set up to push mic to speak, but when the ship departs, the push to speak is released

**Comment by Jack18m** [comment] 2024-01-20 00:06
and If you enable Ghost while dead and return to the player state, hud will be created

**Comment by JustCallMeQuincy** [comment] 2024-01-20 01:05
I'll add this to the list of things to test and I'll post more information as I get it! :D
Thanks for letting us know

**Comment by JustCallMeQuincy** [comment] 2024-01-21 21:03
I was unable to reproduce any of these bugs. 
Could you update to the latest version and provide a recording of the bug happening please?

I will close this issue for now, but if you experience the bug again, feel free to re-open the issue with the provided context.

**Closed by JustCallMeQuincy** 2024-01-21 21:03 UTC
Labels: bug, investigation required

**Comment by Jack18m** [comment] 2024-01-22 03:43
![1](https://github.co
![4](https://github.com/ControlCompany/ControlCompany/assets/157182134/48cb6cb2-79e8-4907-9ed8-763d2eb4acc2)
![3](https://github.com/ControlCompany/ControlCompany/assets/157182134/52a1ab52-fc3a-4811-b6fb-8496e7566d52)

**Comment by Jack18m** [comment] 2024-01-22 03:43
![1](https://github.com/ControlCompany/ControlCompany/assets/157182134/8d742c9d-4f1f-4ccd-be49-e9d97ef6b06f)
![2](https://github.com/ControlCompany/ControlCompany/assets/157182134/0484976b-5240-4774-a1f2-0174678d042f)
![3](https://github.com/ControlCompany/ControlCompany/assets/157182134/e21ad2dc-5e59-403e-bc69-942e6a3c48ed)
![4](https://github.com/ControlCompany/ControlCompany/assets/157182134/838eebe7-1103-45f8-a5a5-1fafd0acf6b8)

**Comment by Jack18m** [comment] 2024-01-22 03:48
I tested it on VoiceHUD mode, and the microphone turned on automatically, and In the last picture, if I die, I turn on ghost mode and go back to normal, Hud comes out like now
