### ISSUE TITLE
Allow other players to control monsters

### ISSUE THREAD

**Issue by Kappet67** [ControlCompany/ControlCompany#157] opened 2024-02-02 21:31 UTC
It sucks that other players can't control the monsters and it ruined the experience for my friends that they weren't able to control them

It would be nice if there was an option in the config to allow other players to control the monsters too or something similar

**Comment by JustCallMeQuincy** [comment] 2024-02-02 21:49
Duplicate of #2 
Feel free to add anything to that thread, regarding this subject

**Closed by JustCallMeQuincy** 2024-02-02 21:49 UTC
Labels: duplicate
