### ISSUE TITLE
More People With Control

### ISSUE THREAD

**Issue by SK3V1X** [ControlCompany/ControlCompany#119] opened 2024-01-20 01:56 UTC
**Is your feature request related to a problem? Please describe.**
Only host can control monsters and it would be very epic if multiple people could.

**Describe the solution you'd like**
The host should be able to give someone else with the mod the ability to also control monsters for double the trolling potential.

**Additional context**
My friend and I want to troll our friend group, so being able to both control monsters would be quite W.

**Comment by Axodouble** [comment] 2024-01-20 19:34
^^ 
I think it would be amazing if the host could enable / disable letting players select to play monsters whenever, or letting them control already existing monsters if the die to them for example. I think that that would be incredibly fun for many players.

**Comment by JustCallMeQuincy** [comment] 2024-01-21 16:54
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed by JustCallMeQuincy** 2024-01-21 16:54 UTC
Labels: duplicate
