### ISSUE TITLE
Allow non host to play monster

### ISSUE THREAD

**Issue by terminator-97** [ControlCompany/ControlCompany#110] opened 2024-01-18 13:18 UTC
**Is your feature request related to a problem? Please describe.**

It would be cool to add a setting to allow also other players to play as monster. (only who has the mod)

**Describe the solution you'd like**

Add a config or a key (for example num 7) that allows everyone who has the mod to play the monster.

**Additional context**

This feature would improve the mod a lot to have much more fun.

**Comment by JustCallMeQuincy** [comment] 2024-01-18 16:41
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed** 2024-01-18 16:42 UTC
Labels: duplicate
