### ISSUE TITLE
Question will this ever be just client side to use in other lobbys with permission obviously

### ISSUE THREAD

**Issue by Pogman15** [ControlCompany/ControlCompany#48] opened 2024-01-13 22:49 UTC
cause i hate waiting for lobbys i get like 12 matches at most

**Comment by Kelkios** [comment] 2024-01-13 23:28
Mainly you probably shouldn't be using this mod against people you don't know

As for using in other people's lobbies it'd probably be impossible, the client probably can't effect the AI of individual creatures, nor could it control them I don't think

**Comment by Magmabot16** [comment] 2024-01-14 03:10
As I said on another post requesting this, I think being able to use it in other people's lobbies would be a bad idea without adding a limitation like requiring the host to have it too. Otherwise it could lead to people using it to harass and ruin other people's lobbies.

**Comment by JustCallMeQuincy** [comment] 2024-01-14 11:26
A good implementation of this could be to give the host a configuration option to enable/disable the others in the lobby (with the mod) to use it.
Then a configuration for maximum how many monsters can be player controlled (the host would probably have a reservation)

**Comment by JustCallMeQuincy** [comment] 2024-01-15 16:57
Closing this issue since it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed by JustCallMeQuincy** 2024-01-15 16:57 UTC
