### ISSUE TITLE
multiperson and no spawn

### ISSUE THREAD

**Issue by Aris-728** [ControlCompany/ControlCompany#128] opened 2024-01-22 23:39 UTC
I'll keep this as simple as I can. I want toggles for players other than the host to be able to control, for control to be locked to AFTER the player dies, and for monster spawning to be turned off. Basically, dead players may choose a monster that is ALREADY ON THE MAP to play as after dying, to make the game continue to be fun instead of forcing the player to just sit around and wait, if they've fucked up.

**Comment by JustCallMeQuincy** [comment] 2024-01-23 00:14
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2
Feel free to post your idea in the comments there!

**Closed by JustCallMeQuincy** 2024-01-23 00:14 UTC
Labels: idea
