### ISSUE TITLE
I used the Baboon Hawk (experimental feature i think) and when i changed to the player i can't do actions (can use the key E, can't change slots, etc

### ISSUE THREAD

**Issue by TomasFire2** [ControlCompany/ControlCompany#147] opened 2024-01-28 20:41 UTC
**Describe the bug**
I used the Baboon Hawk (experimental feature i think) and when i changed to the player i can't do actions (can use the key E, can't change slots, etc

**To Reproduce**
change to the baboon hawk with the experimental feature (0) and grab a boombox, then change to the player, now you can't use the E key and you can't change slots

**Expected behavior**
Everything normal, that i could use the E that i could change slots

**Mod version (please complete the following information):**
V1.1.3

**Additional context**

**Comment by JustCallMeQuincy** [comment] 2024-01-28 20:44
Duplicate of #146

**Closed by JustCallMeQuincy** 2024-01-28 20:44 UTC
Labels: bug, duplicate
