### ISSUE TITLE
A voice activity config / feature for monsters.

### ISSUE THREAD

**Issue by Hna1243** [ControlCompany/ControlCompany#164] opened 2024-02-06 23:20 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
this sounds extremely difficult. But would it be possible for the mod to have an option where voice activity works as a monster? A strange feature but hear me out. Imagine being able to lure your friends in with very realistic speaking and talking. And not just something like the skin walker mod that simply just records your voice and plays it back.

**Additional context**
I’m unsure if this is a duplicate.

**Comment by JustCallMeQuincy** [comment] 2024-02-07 01:15
Thanks for you feature request!
It's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/25, so feel free to add your own suggestions and ideas over there!

Closing this now

**Closed by JustCallMeQuincy** 2024-02-07 01:15 UTC
Labels: duplicate
