### ISSUE TITLE
Switching Targets

### ISSUE THREAD

**Issue by Ruvexai** [ControlCompany/ControlCompany#59] opened 2024-01-14 17:17 UTC
When someone dies, they do not register as a target, this is bad for long-term games when your trying to troll ur friends but gets rlly annoying quickly

**Comment by Ruvexai** [comment] 2024-01-14 17:30
and when i mean they dont register they dont register even if there alive after dying

**Comment by JustCallMeQuincy** [comment] 2024-01-14 18:56
I will test this soon and add more info here once I have it

**Comment by JustCallMeQuincy** [comment] 2024-01-21 21:07
I was unable to reproduce this bug.
Can you update to the latest version and try to reproduce this?

If you can, please (if possible) provide a video of the bug happening.

Closing this issue, assuming it's been resolved in one of the latest updates, feel free to re-open if you can reproduce it.

**Closed by JustCallMeQuincy** 2024-01-21 21:07 UTC
Labels: bug, investigation required
