### ISSUE TITLE
Walking Across Gaps

### ISSUE THREAD

**Issue by ShadowmeC3** [ControlCompany/ControlCompany#116] opened 2024-01-19 17:07 UTC
Right now you fall down into the pit which makes people know it's you.

It would be nice to make a visible path across to you, but be invisible for them.

So that you can chase your friends across gaps and they cant just get away.

**Comment by JustCallMeQuincy** [comment] 2024-01-19 22:22
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/10

**Closed by JustCallMeQuincy** 2024-01-19 22:22 UTC
Labels: duplicate
