### ISSUE TITLE
Bug Report/Feature

### ISSUE THREAD

**Issue by macncheesebeans** [ControlCompany/ControlCompany#14] opened 2024-01-12 18:12 UTC
Hoarding bugs randomly aggro when there are no players around.
Hoarding bugs aggro very inconsistently when close to other players and stay aggro for a very long time.
Being able to toggle their aggressive mode would be a great feature.

**Comment by Magmabot16** [comment] 2024-01-12 18:22
I've had the same issue, this would be great. It'd also be nice to have the ability to control when the hoarding bug picks up and drops items.

**Comment by JustCallMeQuincy** [comment] 2024-01-12 18:58
> I've had the same issue, this would be great. It'd also be nice to have the ability to control when the hoarding bug picks up and drops items.

You can control that since V1.0.3

**Comment by klampzlamps** [comment] 2024-01-15 05:17
duplicate of #13 closing in favour of it

**Closed by klampzlamps** 2024-01-15 05:17 UTC
