### ISSUE TITLE
Multi-ControlCompany

### ISSUE THREAD

**Issue by SkullyTM** [ControlCompany/ControlCompany#140] opened 2024-01-26 01:59 UTC
is it possible to make it so the host has the ability to give other people (who have the mod) to be able to control monsters?

**Comment by JustCallMeQuincy** [comment] 2024-01-26 02:30
Closing as it's a duplicate of https://github.com/ControlCompany/ControlCompany/issues/2

**Closed by JustCallMeQuincy** 2024-01-26 02:30 UTC
Labels: duplicate

**Comment by SkullyTM** [comment] 2024-01-26 18:55
oh thank you, didn't know there was already one
